### ISSUE TITLE
Add `babel-plugin-superjson-next` to Blitz

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1043]
### What do you want and why?

I want Blitz apps to use [babel-plugin-superjson-next](https://github.com/blitz-js/babel-plugin-superjson-next) by default so that `getServerSideProps` and `getStaticProps` have superjson serialization.

### Possible implementation(s)

I'm not sure the best way to do this. Can we add it via [our custom webpack config](https://github.com/blitz-js/blitz/blob/canary/packages/server/src/with-blitz.ts)?

One way would be to add our own babel preset. Currently blitz apps have `next/babel` in the babel presets by default. We can add our own babel config so apps would have `blitz/babel` in the config by default.

**Comment by ntgussoni** [comment]
@flybayer  We need to make a release of babel-plugin-superjson-next as I have fixed a bug with static methods and if we implement this right now we'll break `getLayout`

**Comment by flybayer** [comment]
The static method issue should be fixed in 0.1.6: https://github.com/blitz-js/babel-plugin-superjson-next/releases

**Comment by nksaraf** [comment]
I think a Babel preset is the way to go since we can include other custom Babel plugins also if we want to customize the behavior further. I am working on a plugin to help with named exports from the API (#1133), which could also be included in this. For React Native / Expo support also, the Babel plugin is a necessity to transform code before building.
