### ISSUE TITLE
Add automatic query cancelation for when queries become inactive (like off screen)

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1055]
### What do you want and why?

By default React-query let's requests finish if they become inactive. But it does allow you to configure query cancellation. This isn't a big deal, but it's an optimization we might as well make!

### Possible implementation(s)

Implement the [react-query cancellation](https://react-query.tanstack.com/docs/guides/query-cancellation) feature [at this line](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/use-query.ts#L52).

Also need to add that in the `use-paginated-query.ts` and `use-infinite-query.ts` files.

**Comment by hardfire** [comment]
@flybayer let me take this.

**Comment by flybayer** [comment]
@hardfire All yours!

**Comment by hardfire** [comment]
okay, this isn't as straightforward as i initially thought it would be. some observations
 - [here](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/use-query.ts#L52) `queryRpcFn` should be the same as `queryFn` in browser context, but it isn't as [this](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/rpc.ts#L145) should be executed at some point.
 - since the promise is never returned [here](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/rpc.ts#L49) we will have to jump some more hoops so that react query can also call cancel on the promise.

**Comment by flybayer** [comment]
[rpcFn](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/rpc.ts#L152) is what is passed into our `useQuery`. Feel free to add more comments in there! And refactor anything that needs it.

I think what we can do is instantiate the abort controller at [this line](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/use-query.ts?rgh-link-date=2020-09-12T20%3A06%3A29Z#L52) and pass `signal` down through `rpcFn` to `executeRpcCall` where you set it on `fetch`.

Something like this:

```ts
queryFn: (_apiUrl, params) => {
  // Create a new AbortController instance for this request
  const controller = new AbortController()
  // Get the abortController's signal
  const signal = controller.signal

  const promise = queryRpcFn(params, {fromQueryHook: true, signal})

  // Cancel the request if React Query calls the `promise.cancel` method
  promise.cancel = () => controller.abort()

  return promise
}
```

**Comment by hardfire** [comment]
o yeah! i had something similar as well. 
What confused me is that there is a complie step between the useQuery we write and the useQuery we use :D

**Comment by flybayer** [comment]
Yeah, it's a bit tricky to understand!
