### ISSUE TITLE
Opting in to the upcoming breaking changes in tailwind

### ISSUE THREAD

**Issue by pbteja1998** [blitz-js/blitz#1100]
### What do you want and why?

I want the `tailwind.config.js` from [tailwind recipe](https://github.com/blitz-js/blitz/blob/canary/recipes/tailwind) to include the following since these will be breaking changes in the upcoming version and tailwind recommends to opt in to these changes.
```
removeDeprecatedGapUtilities: true
purgeLayersByDefault: true
```

### Possible implementation(s)

How might we do this?
Add the following to [tailwind.config.js](https://github.com/blitz-js/blitz/blob/canary/recipes/tailwind/templates/config/tailwind.config.js)
```js
module.exports = {
    future: {
        removeDeprecatedGapUtilities: true,
        purgeLayersByDefault: true,
    },
    // other stuff
}
```

### Additional context

<img width="1094" alt="Screenshot 2020-09-17 at 11 46 09 AM" src="https://user-images.githubusercontent.com/17903466/93428237-b6b48980-f8dc-11ea-9c79-22c588035a4a.png">

**Comment by pbteja1998** [comment]
Also, it would be good to have an option to include tailwind UI too.

**Comment by flybayer** [comment]
Yes, great suggestion! Thanks.

**Comment by enricoschaaf** [comment]
I would like to work on this, if its okey.😊 I would have set it like this:
```typescript
module.exports = {
    future: "all",
    // other stuff
}
```
That way all future changes that are added are included automatically.
Should we add a flag for Tailwind UI or should that be its own recipe that requires Tailwind? Also Tailwind UI recommends using the Inter font, so I am wondering if it should be included as well. If yes than that adds a lot more complexity because you would very likely want to subset the font which could be tricky.

**Comment by flybayer** [comment]
@enricoschaaf good idea to use "all"! Let's just make this change for this issue, and we can consider the Inter font as a separate issue.

It's all yours!
