### ISSUE TITLE
Can't resolve 'next-transpile-modules' when build target is set to serverless

### ISSUE THREAD

**Issue by LoriKarikari** [blitz-js/blitz#1244]
### What is the problem?

When the build target is set to `serverless` the build fails with `ModuleNotFoundError: Module not found: Error: Can't resolve 'next-transpile-modules' in '/home/lori/dev/projects/streamsbase/app/node_modules/@blitzjs/server/dist'`.

### Steps to Reproduce

1. add `target: "serverless",` to `blitz.config.js`
2. run `blitz build`

### Versions

```
Linux 4.19 | linux-x64 | Node: v14.4.0

blitz: 0.22.1 (global)
blitz: 0.22.1 (local)
```

**Comment by peaonunes** [comment]
To add a bit more context, I was looking at it and narrowed down the usage of `next-transpile-modules` and turns out we only use that in once place:
https://github.com/blitz-js/blitz/blob/0b103bcccaae24ccd8720ed810f8c6d2656724e1/packages/server/src/with-blitz.ts#L60-L69

However, that code path was meant to run only on blitz server project development. It is strange that this is being executed in a blitz app. I quickly tried to add some console around that block of code, but could not get it printed in the output which is strange. In addition to that, I tried promoting the package as a `dependency` of `server` rather than `devDependency`, that was also unsuccesfull.
https://github.com/blitz-js/blitz/blob/99bf898cdc7f37e431b0c3903da6dc5fb66d8aa4/packages/server/package.json#L70-L73

I'm not sure if my set up is wrong so the changes I made would not reflect in the generated app or if there is any other implicit usage of the package that is leading to the issue...

Either way there seems to have some limitations around the setup described in their FAQ (https://github.com/martpie/next-transpile-modules#faq).

Could it be the case that the `serverless` target never worked so far?

**Comment by LoriKarikari** [comment]
> Could it be the case that the `serverless` target never worked so far?

I never tried setting the `serverless` target before so I have no idea if it ever worked.

**Comment by flybayer** [comment]
@LoriKarikari were you using blitz from npm with this issue or via `yarn link blitz` ?

**Comment by LoriKarikari** [comment]
@flybayer the npm version

**Comment by peaonunes** [comment]
Yeah, tried the npm version and the local version.
The npm version on a brand new folder the error is:
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'next-transpile-modules' in '/Users/-/Code/app/node_modules/@blitzjs/server/dist'
```

The local version using the link and creating an app in the `examples` folder of blitz raises a different error 🤷 :
```
/Users/-/Code/blitz/node_modules/fsevents/fsevents.node 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

**Comment by lcswillems** [comment]
I have the exact same issue! I can't target serverless because of 'next-transpile-modules'

**Comment by flybayer** [comment]
This *should* be fixed in the next patch release

**Comment by flybayer** [comment]
should already be fixed for some time now
