### ISSUE TITLE
Fix `@prisma/client` being included in the client side bundle during development

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#13]
The current `core` and `first-demo` code runs in production on Zeit now, but it fails during local development:

```
Failed to compile

/Users/b/c/blitz/node_modules/@prisma/client/runtime/index.js
Module not found: Can't resolve 'child_process' in '/Users/b/c/blitz/node_modules/@prisma/client/runtime'
```

- [Prisma docs on what `@prisma/client` is and how it works](https://github.com/prisma/prisma2/blob/master/docs/prisma-client-js/codegen-and-node-setup.md)
- [A blog post describing what's happening here](https://arunoda.me/blog/ssr-and-server-only-modules)

This issue is up for grabs!

**Comment by toddgeist** [comment]
is there going to be a next.config.js in the root of core?

**Comment by toddgeist** [comment]
nevermind - I see what the plan is

**Comment by flybayer** [comment]
I think Blitz will provide a next.config.js wrapper

**Comment by toddgeist** [comment]
you already have a next.config.js in the example.

**Comment by toddgeist** [comment]
I'll take a shot at this.

**Comment by toddgeist** [comment]
I have some work to do to get up to speed though. haven't used TypeScript in a while, and postgres in years....

So if anyone else wants this issue, have at it.  :-)

**Comment by flybayer** [comment]
You can switch to sqlite. Change to this in `prisma/schema.prisma`
```
datasource db {
  provider = "sqlite" // other options are: "mysql" and "sqlite"
  url = "file:./dev.db"
}
```

**Comment by jimthedev** [comment]
I have a PR for this incoming.

**Comment by flybayer** [comment]
@jimthedev yay, thank you!!

**Comment by jimthedev** [comment]
Ok a couple of things. The webpack docs indicate you should be able to just use 

```
if (!isServer) {
      config.resolve.alias['@prisma/client'] = false
}
```

Unfortunately the version of webpack being used seems to want a string and will not accept `false`. It seems that perhaps in the future the right approach may be to use `false` but that won't work for now.

I also looked into the approach using the IgnorePlugin but was getting some strange errors where webpack was putting a ! into the code for the frontend and saying it could not find the modules '@prisma/client` so in that case it seems that it properly ignored the module but that resulted in an error since we aren't providing the module by other means. 

So what can we do? As the article @flybayer mentioned we can resolve to a noop file (an empty file) and everything works well. Effectively it operates as a noop until webpack supports the `false` value. Happy to have others try to confirm but wanted to share what I'd found.

**Comment by flybayer** [comment]
I just posted in the Prisma slack. We'll see what they say.
