### ISSUE TITLE
blitz db seed won't run code imported from other files

### ISSUE THREAD

**Issue by aaronfulkerson** [blitz-js/blitz#1417]
### Steps to Reproduce

1. Bootstrap a new app and run `blitz db seed` after importing something into seeds.ts from another file such as hashPassword from auth-utils.

### Versions

```
0.25.0-canary-1
```

### Other

Please include applicable logs and screenshots that show your problem.

**Comment by isoppp** [comment]
I can't reproduce this in my local with 0.25.0-canary.1 with a brand new project.

Could you run `blitz --version` and `yarn run blitz --version` and then copy and paste the logs if this still happens. Your seed file is also helpful.
As far as I remember it fixed with `0.25.0-canary.0`.
I guess your global blitz-cli is 0.24.x version or something like less than the canary version.

**Comment by aaronfulkerson** [comment]
I didn't install with yarn, that's probably the difference. I'll check it out tomorrow.

**Comment by aaronfulkerson** [comment]
This appears to be fixed in the full 0.25.0 release. Sorry about that!
