### ISSUE TITLE
query options type no longer accepts forceFetchOnMount

### ISSUE THREAD

**Issue by zenhob** [blitz-js/blitz#1471]
### What is the problem?

After upgrading to Blitz 0.25.0 my build failed with:

```
Type error: Argument of type '{ forceFetchOnMount: boolean; }' is not assignable to parameter of
type 'QueryOptions<Cafe, Error>'.
```

After some digging, I found [this change](https://github.com/blitz-js/blitz/commit/25df2c0c29e5347d92d5a0b94e20af9565e5adc9#diff-5c9e08f588dcc289a26adbf4ddc10d25ddf10d8be027be705da6c838ca7293cdL36) that modifies the type definition of this argument, that's the only possible clue I could find.

### Steps to Reproduce

1. pass the `forceFetchOnMount` option to a `useQuery` call
2. run `blitz build`
3. Observe the error above

### Versions

```
Linux 5.4 | linux-x64 | Node: v14.8.0

blitz: 0.25.0 (local)

  Package manager: npm
  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 461.94 MB / 15.33 GB
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.8.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: 2.10.2 => 2.10.2
    @prisma/client: 2.10.2 => 2.10.2
    blitz: 0.25.0 => 0.25.0
    react: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530
    react-dom: 0.0.0-experimental-4ead6b530 => 0.0.0-experimental-4ead6b530
    typescript: 3.9.7 => 3.9.7
```

**Comment by zenhob** [comment]
downgrading to `0.25.0-canary.2` fixes this issue.

**Comment by flybayer** [comment]
Hey @zenhob, sorry about that. This is because of https://github.com/blitz-js/blitz/pull/1430. We had to downgrade react-query because of concurrent mode bugs people were experiencing.

By default data is considered stale immediately, so every mount will refetch data. Therefore you don't need `forceFetchOnMount` unless you are using a non-standard stale time.

### Workaround for 0.25.0

This is a workaround to use a newer version of react-query, but be aware that you may experience bugs related to concurrent mode.

1. Use Yarn instead of npm
2. Add the following to package.json and re-run `yarn`
```
"resolutions": {
  "react-query": "2.23.0"
}
```
3. Add the following in `_app.tsx`
```ts
import {Router} from 'blitz'

Router.events.on("routeChangeComplete", async () => {
  await queryCache.invalidateQueries()
})
```

**Comment by flybayer** [comment]
@zenhob did that work for you?

**Comment by MrLeebo** [comment]
I'm gonna interpret the lack of response to mean it worked.
