### ISSUE TITLE
Can't import from queries/mutations via path alias

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1495]
### What is the problem?

https://github.com/blitz-js/blitz/pull/1456 added ability to import code from queries/mutations, but it broke the ability to import from queries/mutations via path alias.

### Steps to Reproduce

1. Add path alias in tsconfig

```json
{
  "compilerOptions": {
    "paths": {
      "@queries/*": ["app/queries/*"]
    }
  },
}
```

2. Make two queries in `app/queries/`
3. Export a named function from one query
```ts
// app/queries/query1.ts
export const name = 'hello'
```
4. Try to import that in the other query - build fails
```ts
// app/queries/query2.ts
import {name} from '@queries/query1'
```

But it works if you import via absolute or relative path.

### Versions

```
latest canary
```

cc @Skn0tt

**Comment by piotrski** [comment]
The issue is probably that ts compiler can resolve those aliases from `tsconfig` but js runtime can't. I think you have to use something like [tsconfig-paths](https://github.com/dividab/tsconfig-paths) to rewrite those import paths. There is also a [webpack plugin](https://github.com/dividab/tsconfig-paths-webpack-plugin) we could add.

**Comment by flybayer** [comment]
I realized today that importing via alias does actually work in dev (`blitz start`), but fails at `blitz build` with a TS error. So I think this is just a Type issue in our generated code
