### ISSUE TITLE
pipe.authorize() doesn't work as type guard

### ISSUE THREAD

**Issue by merodiro** [blitz-js/blitz#1820]
### What is the problem?
The new `pipe.authorize()` doesn't work as a type guard like `ctx.session.$authorize()`

### Steps to Reproduce

create a new mutation with this code
```js
export default pipe.resolver(pipe.zod(CreatePost), pipe.authorize(), async ({ body }, ctx) => {
  const post = await db.post.create({
    data: {
      body,
      userId: ctx.session.userId,
    },
  })

  return post
})
```

### Expected
`ctx.session.userId` to always be `number`

### Current
`ctx.session.userId` is `number | null`

### Versions

```
blitz: 0.30.0-canary.2 (local)

  Package manager: yarn 
  System:
    OS: Linux 4.19 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 11.53 GB / 12.44 GB
    Shell: 3.1.0 - /usr/bin/fish
  Binaries:
    Node: 15.6.0 - ~/.config/nvm/15.6.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.4.0 - ~/.config/nvm/15.6.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/cli: ~2.15 => 2.15.0 
    @prisma/client: ~2.15 => 2.15.0 
    blitz: 0.30.0-canary.2 => 0.30.0-canary.2 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.1.3 => 4.1.3
```

**Comment by flybayer** [comment]
NOTE: in canary branch, this is now `resolver.authorize` in `packages/core/src/resolver.ts`

**Comment by hasparus** [comment]
**how I thought about it**

So... there's no way to use `asserts` or `is` on a `ctx` parameter, because there is no "ctx" variable in common scope, right? 
`Ctx` is set in `PipeFn` type, and that's it, no function earlier in the chain can modify it...

**end result**

![image](https://user-images.githubusercontent.com/15332326/106328956-f1fa9800-6280-11eb-854e-a6dda6c5b9c1.png)

**new authorize function**

![image](https://user-images.githubusercontent.com/15332326/106329251-6b928600-6281-11eb-8407-89536822cd1f.png)

**and how I did it**

![image](https://user-images.githubusercontent.com/15332326/106328791-b52ea100-6280-11eb-81ae-d952e1bf5ac8.png)

Types for `pipe` are going to be even more hideous than they are right now, but this is the only way I see using `ctx` as the second param. (Alternatively, you could use classic function expressions and assign `ctx` to [`this`](https://gist.github.com/karol-majewski/1d2aee6b25892c7285555fda31327ba8), but I'd rather have hideous types than hideos userland API).

I'll send a PR in a moment.

**Comment by flybayer** [comment]
@hasparus YOU ARE A CHAMPION!! THANK YOU!!!

![image](https://user-images.githubusercontent.com/8813276/106342905-cec7ec80-6270-11eb-9ed9-43021722d5be.png)

**Comment by flybayer** [comment]
Released in https://github.com/blitz-js/blitz/releases/tag/v0.30.0-canary.4
