### ISSUE TITLE
Generate types for /pages routes

### ISSUE THREAD

**Issue by remjx** [blitz-js/blitz#2023]
### What do you want and why?

TypeScript types for routes in /pages

For example, given `app/pages/user/settings.tsx`, generate `type UserSettingsRoute = "/user/settings"`

This way, we can reference the route in a type-safe manner instead of relying on tests to catch the error.

### Possible implementation(s)

Create a `blitz generate types` command that scans the directory structure for /pages routes, and maps the routes to TypeScript types, e.g.

```route-types.ts
declare namespace BlitzRoutes {
  type AppPagesIndexRoute: "/"
  type UserSettingsRoute: "/user/settings"
}
```

to be used like this:

```
const homeRoute: BlitzRoutes.AppPagesIndexRoute = "/"
return <Link href={homeRoute} />
```

#### Static paths
Given `app/pages/index.tsx`, generate `type IndexRoute = "/"`
Given `app/pages/user/settings`, generate `type UserSettingsRoute = '/user/settings'`

#### Dynamic paths
I don't think this is possible since TypeScript doesn't have a way to use wildcards in string types, i.e. `type String = "app/users/*wildcard*/settings`

**Comment by remjx** [comment]
@engelkes-finstreet's current approach:

```
export const routes = {
  index: "/",
  customers: {
    index: "/customers",
    new: "/customers/new",
    view: (id: number) => `/customers/${id}`,
    edit: (id: number) => `/customers/${id}/edit`,
  },
  users: {
    index: "/users",
    edit: (id: number) => `users/${id}/edit`,
  },
}
```

**Comment by Skn0tt** [comment]
I like this idea! We could then use the generated type in our `Link` adaptation.

What file should we write these types into? Maybe into the .blitz directory?

**Comment by flybayer** [comment]
Oh, this is a fabulous idea!! And I think we can take it a step further to provide routes as a JS object so that you can do something like this:

```tsx
import {Routes} from 'blitz'

<Link href={Routes.LoginPage}>
```

Basically do the same thing as Prisma but for routes.

It would be better if we can generate the field/type name based on something other than the filepath because ideally you can reorganize your files and routes without changing your usage of `Routes`. The first thing that comes to mind is use the name of the default export component in the page. I.e. `export default UserShowPage` would be `Routes.UserShowPage`, regardless of where it is at in the file system.

**Comment by hasparus** [comment]
> Oh, this is a fabulous idea!! And I think we can take it a step further to provide routes as a JS object so that you can do something like this:

If you go filepath-based way, I kinda dislike runtime emit. It's not a hard preference, but I feel I'd rather write a string inside href without any import — it could be still typechecked and autocompleted by Link props. 

Made sth in this theme once — https://github.com/hasparus/strict-routes

---

> It would be better if we can generate the field/type name based on something other than the filepath because ideally you can reorganize your files and routes without changing your usage of Routes.

This is **smart**. Routes are an implementation detail, what the user wants to do is navigate to a page or a "view".


---

> I don't think this is possible since TypeScript doesn't have a way to use wildcards in string types, i.e. type String = "app/users/*wildcard*/settings

@remjx This is possible since TS 4.1 — https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html

**Comment by flybayer** [comment]
> So, just to make sure I understood you, the pseudocode would be

Yes. So the default export component name would have to be globally unique in this case

**Comment by daganomri** [comment]
> Yes. So the default export component name would have to be globally unique in this case
What about in the case of anonymous default exports? Is it possible to enforce named default exports?

**Comment by flybayer** [comment]
@daganomri we currently have a lint rule that errors (or at leasts warns) on anonymous default exports. So we can totally enforce that

**Comment by Skn0tt** [comment]
I'd love to work on this!

What's the best place to emit into? Should the resulting dictionary be checked into Git or not?

**Comment by flybayer** [comment]
@Skn0tt well, unless we have a better reason, I think it makes sense to follow exact same pattern as prisma and generate it to `node_modules/.blitz` and we can use a postinstall hook like them to generate it

**Comment by flybayer** [comment]
But I guess it could be nice way to easily see all routes in your app if it's checked into git 🤔  (as long as it's relatively clean to look at)
