### ISSUE TITLE
Blitz breaks Shallow Routing of Next.js

### ISSUE THREAD

**Issue by medihack** [blitz-js/blitz#2047]
### What is the problem?

With [Shallow Routing](https://nextjs.org/docs/routing/shallow-routing) it is possible to update a path without losing component state. The components get rerendered, but will not be destroyed and created again. This works fine in Next.js, but Blitz.js breaks this.

### What are detailed steps to reproduce this?

I created two little different repositories that demonstrate the problem:
https://github.com/medihack/blitz-shallow
https://github.com/medihack/next-shallow

When clicking the button and watching the console you'll see that TestComponent is destroyed and recreated in Blitz.js, but not in Next.js.

### Run `blitz -v` and paste the output here:

```
Linux 4.15 | linux-x64 | Node: v12.19.0

blitz: 0.30.4 (global)
blitz: 0.30.6 (local)

  Package manager: yarn 
  System:
    OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
    Memory: 2.12 GB / 15.66 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.19.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.8 - /usr/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.17 => 2.17.0 
    blitz: latest => 0.30.6 
    prisma: ~2.17 => 2.17.0 
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0 
    typescript: 4.x => 4.2.2
```

**Comment by flybayer** [comment]
Hey @medihack, I'm fairly certain this is because of react concurrent mode which we have enabled by default in blitz.

Can you try this in the next app and see if it still works or not?
1. `npm i react@experimental react-dom@experimental`
2. Add following to `next.config.js`
```js
module.exports = {
  experimental: {
    reactMode: "concurrent",
  },
}
```

And you can disable that in blitz with this in blitz.config.js:

```js
module.exports = {
  experimental: {
    reactMode: "legacy",
  },
}
```

You can also try `"blocking"`

**Comment by medihack** [comment]
Unfortunately not. It fails with `legacy` and `blocking` mode in those demos (and also in my main project). The components still get destroyed.

**Comment by medihack** [comment]
Ok, I also tried it now in the Next sample. It still works there as expected (in blocking and concurrent mode).

**Comment by flybayer** [comment]
Ok interesting, thanks for checking. Then my next guess is that it's caused by our `getLayout` pattern or by our https://github.com/blitz-js/blitz/blob/canary/packages/core/src/blitz-app-root.tsx components which we add via a babel plugin

**Comment by medihack** [comment]
Disabling the persistent layout (and removing the suppressFirstRenderFlicker) also seems to have no effect (components still get destroyed with shallow routing).

I updated the Blitz example to be more simplistic (without persistent layout) and with legacy mode.

**Comment by sakulstra** [comment]
not sure if this sheds more light on the issue -as i didn't immediately find this issue here's my reproduction as well :sweat_smile: 

I ripped everything off my app(middlewares, layout and so on), replaced all the needed elements with direct next imports, except for:
```
import Document, { Html, Head, Main } from "next/document"
import { BlitzScript } from "blitz"
```
Because without BlitzScript nothing will render due to cookie related errors.

Then I crated the most simple page I could think of to reproduce the issue:
```
import { useRouter } from "next/router"
import React from "react"

export default function Test() {
  const { replace } = useRouter()

  const handleChange = (event) => {
    // replace({ query }, undefined, { shallow: true })
    replace(`/test?p=${event.target.value}`)
  }

  return <input onChange={handleChange} />
}
```
Here's the reproduction: https://github.com/sakulstra/blitz-issues/blob/master/app/pages/test.tsx
