### ISSUE TITLE
Add @testing-library/user-event to Blitz.js by default

### ISSUE THREAD

**Issue by emgoto** [blitz-js/blitz#2253]
### The problem
I installed the latest version of testing-library/user-event (13.1.5). 

However, when I tried to use this library I ran into the following error:

`+userEvent element.ownerDocument.createRange is not a function`

I managed to fix this by downgrading to an older version, ^12.8.3. (I just randomly chose this version number because it's what I was using on another non-Blitzjs repo).

I'm not sure if there's some sort of mismatch with the latest version of user-event vs whatever versions of testing-library that Blitz.js is using.

### What do you want and why?

Since testing-library already comes preinstalled with Blitz, I think it may be worth preinstalling user-event as well.

### Output of blitz -v

```
macOS Mojave | darwin-x64 | Node: v12.20.0

blitz: 0.33.1 (global)
blitz: 0.33.1 (local)

  Package manager: yarn 
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 78.34 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.20.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.19 => 2.19.0 
    blitz: 0.33.1 => 0.33.1 
    prisma: ~2.19 => 2.19.0 
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    typescript: ~4.1 => 4.1.5 
```

**Comment by MrLeebo** [comment]
I have some hesitations about this and the practice of bundling dependencies that Blitz doesn't need but to invite users to play with them. Perhaps down the road the matter will be different, but at this juncture it seems to me that the value added may not outweigh the additional maintenance cost of including this library. It is probably better for this to be something that users who want it can install for themselves, at least until it has a track record for stability.

Adding a package to a framework like Blitz requires more work than just the energy it takes to add the package to the default app template; every release has the potential of impacting tests and when that happens after upgrading a Blitz app, the issue will be created as a Blitz issue, not as a testing-library issue, because you would upgrade Blitz and then it broke. We can redirect users to those repos, but then we become the traffic controllers for issues stemming from these downstream dependencies. Since user-events sits at the crossroads between browser user events (highly prone to changes) and unit testing (highly prone to breaking) it'll generate a lot of traffic.

That said, if someone wants to create a PR for this and is willing to accept that they may become a code owner/traffic cop when those issues arise, then please accept my blessing 🍹

**Comment by flybayer** [comment]
I think let's close this for now for lack of demand. Can always revisit down the road.
