### ISSUE TITLE
"Routes.SignupPage is not a function" when using monorepo

### ISSUE THREAD

**Issue by niklasgrewe** [blitz-js/blitz#2272]
### What is the problem?

When i try run my blitz app inside my yarn workspace, i get the following webpack error:

```
_blitzjs_core__WEBPACK_IMPORTED_MODULE_6__.Routes.SignupPage is not a function
```

### Paste all your error logs here:

```
_blitzjs_core__WEBPACK_IMPORTED_MODULE_6__.Routes.SignupPage is not a function

pages/index.tsx (37:27) @ UserInfo

  35 | return (
  36 |   <>
> 37 |     <Link href={Routes.SignupPage()}>
     |                       ^
  38 |       <a className="button small">
  39 |         <strong>Sign Up</strong>
  40 |       </a>
```

### Paste all relevant code snippets here:

my root `package.json` looks like this:

```
{
  "name": "blitz-monorepo",
  "private": "true",
  "version": "1.0.0",
  "workspaces": {
    "packages": [
      "packages/*"
    ]
  },
  "scripts": {
    "web": "yarn workspace web"
  }
}
```

### What are detailed steps to reproduce this?

1. create a new folder like `blitz-monorepo`
2. create a subfolder `packages`
3. install a new blitz app inside `packages`
4. remove `node_modules` folder from blitz app
5. create a root `package.json` like above
6. run `yarn install && yarn workspace <blitzAppName> dev`

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-arm64 | Node: v15.14.0

blitz: 0.34.3 (global)
blitz: 0.34.3 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
    Memory: 1.05 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.14.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.7.6 - /opt/homebrew/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found
```

**Comment by Skn0tt** [comment]
@niklasgrewe thanks for reporting!

It seems to be caused by: 
https://github.com/blitz-js/blitz/blob/4bb6ded00cfa18180b36ec185b92cfc982e71a9f/packages/server/src/stages/route-import-manifest/route-import-manifest.ts#L110

This will render into `packages/app/node_modules/.blitz` instead of `node_modules/.blitz`.

The obvious fix would be to adapt the [postinstall logic](https://github.com/blitz-js/blitz/blob/canary/packages/blitz/scripts/postinstall.js). @flybayer do we already detect the monorepo root somewhere else, that could be used here?

**Comment by flybayer** [comment]
@Skn0tt no, we haven't done any monorepo stuff until this
