### ISSUE TITLE
Add cli command: blitz test watch

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#23]
- [ ] `blitz test watch` should run the `test:watch` package.json script.
- [ ] `blitz tw` should run `blitz test watch`
- [ ] Add tests

**Comment by tsawan** [comment]
@flybayer apparently oclif doesn't support `blitz test watch` as a separate command (with a space) out of the box, since you also want alias `blitz tw`. 
So we have 2 options.
a) extend `blitz test` command to support `watch` argument. but then we can't have alias `blitz tw`.
b) create a new command `blitz test:watch` (with a colon), with an alias `blitz tw`.

let me know your thoughts?

**Comment by flybayer** [comment]
Ok, probably not worth that. Can we do `blitz t w` with oclif?

**Comment by tsawan** [comment]
we can probably do `blitz t w` but that may impact the semantics on context with other commands. I guess we have to visit these commands anyway in near future so let's start with simple case(s) for now.

**Comment by flybayer** [comment]
> that may impact the semantics in context with other commands

Can you elaborate?

**Comment by tsawan** [comment]
I guess single letter aliases make sense only for the command but not for parameters and it may become difficult to implement the same for other more complex commands (even if we can manage this for simpler case like test watch).

**Comment by tsawan** [comment]
Ok, I've just played around with oclif's topic support and it's not very flexible. we can have commands like test:watch (here test is main command and watch is a sub-command) but it doesn't support t:w.
So I suggest we modify current test command to add support for --watch flag (it will also work with -w) and be done with this?

**Comment by tsawan** [comment]
just to clarify further, as soon as we implement topic (sub-command) aliases doesn't work for any combination of main+sub-command.

**Comment by flybayer** [comment]
Bummer. The more I think about it, the more I really want sub-command alias support. Will also use it with generators like `blitz g m` to generate a model.

This may be the kicker to switch off oclif. See the slack convo in #dev-cli

**Comment by tsawan** [comment]
yeah, I read the whole convo and think we rushed off too early towards oclif. Probably should've listed all scenarios and started off with writing tests.
just read commander intro. and it is more open than oclif. We can still try oclif with a custom patch (I've found a patch from adobe that supports space separated topic commands).

**Comment by tsawan** [comment]
@flybayer since the oclif testing issue is resolved, I can send a PR for this and #24. Or you want to hold these till oclif's fate is decided?

**Comment by flybayer** [comment]
So right now we can do `blitz test watch` and `blitz t watch`, but we just can't alias `watch`, correct?

**Comment by tsawan** [comment]
I now think we went too deep in topics/sub-command route. 
Please review this PR #50.

It doesn't support t:w (since colon is used by oclif for sub-commands).
Ideally I would've liked to use flags but oclif uses hypens (e.g., --version or -v) to distinguish between a flag and a positional argument. 

If you are happy with this PR, I can next look into #24.
