### ISSUE TITLE
Add blitz generate model

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#234]
**What do you want and why do you want it?.**

We want to add a model generator that:

- Adds a model & attributes to `schema.prisma`
- (Future) scaffolds model validation
- (Future) scaffolds model authorization

All of the commands listed here should result in a valid, working schema file.

```
blitz generate model task email:string:unique name:string? age:int
```

**The field arguments have this format: `fieldName:fieldType:fieldAttribute`**

- `fieldName`:
	- passed through exactly
	- can have `?` suffix that is passed through to schema file
- `fieldType`:
	- CLI will automatically PascalCase and singularize it
	- Ex: `string`, `boolean`, `int`, `float`, `dateTime`
    - Also supports relation models: `product`, `product[]`
- `fieldAttribute`:
    - Passed through and set as `@fieldAttribute` on the field
    - Can have optional parameter in brackets
    - Example: `int:unique` -> `Int @unique`
    - Example: `boolean:default[false]` -> `Boolean @default(false)`

**Relations:**

- One-to-one
```
blitz generate model chair name:string table:table
blitz generate model table name:string chair:chair
```

- One-to-many
```
blitz generate model project name:string tasks:task[]
blitz generate model task name:string project:project
```

- Many-to-many
```
blitz generate model project name:string categories:category[]
blitz generate model category name:string projects:project[]
```

These must all generate all the code needed for the relation, like:
```
  author    User?  @relation(fields: [authorId], references: [id])
  authorId  Int?
```

**These field arguments must also work with the higher level generators like this:**
```
blitz generate all task email:string:unique name:string? age:int
```

**Additional info**

- Prisma schema docs: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/prisma-schema-file
- Prisma schema spec: https://github.com/prisma/specs/tree/master/schema
- We need to use `[]` for the fieldAttribute parameter instead of `()` because `()` is for command substitution in the fish shell

**Comment by aem** [comment]
This can probably be done incrementally to get users an MVP as quickly as possible, rather than trying to support all of this at once. My existing solution gets us close to the MVP. The one addition I'd like to make would be rather than parsing the values inline in the ModelGenerator, to have a `PrismaField` class that can take the colon-delimited string and parse it into a complete line of text for the prisma schema file. This gives a natural place to extend the existing functionality into supporting foreign keys and other directives.

**Comment by Blanen** [comment]
Is it not simpler for a developer to have the schema being the sole source of truth by default rather than the cli options that creates the schema? Then you could simply hand the model name (and other cli options) to a pluggable system that by default looks up the prisma definitions. Meanwhile another plugin there could look it up from a remote source or whatever.

With a pluggable system you could also have the currently proposed idea by default.

**Comment by flybayer** [comment]
@Blanen yes, I think when generating other things like queries/pages, we'll read the schema as source of truth.

But this feature issue is for generating the actual schema. It's just a nice to have for easily adding models to your schema from the CLI without opening the schema file.
