### ISSUE TITLE
Build config and custom server during `blitz build`

### ISSUE THREAD

**Issue by andreasasprou** [blitz-js/blitz#2354]
### What do you want and why?

When creating a production Dockerfile, I don't want to include all my source files required to build `server.ts` (or `blitz.config.ts`!).

### Possible implementation(s)

**For custom server**
Build custom server during `blitz build` and use those built files when running `blitz start`:

- modify `getCustomServerPath` to include `.blitz/custom-server.js`
- modify `startCustomServer` to run `.blitz/custom-server.js` if it exists and we're running in production
- modify [build script](https://github.com/blitz-js/blitz/blob/bf7eed62bd1aaf8a23779eb02e19a06cb5ffc0ff/packages/server/src/build.ts) to build custom-server and copy files (see `saveBlitzVersion` and adjust to copy to `.blitz/custom-server.js`)

Reflect on why the files currently reside in `.blitz` and not `.blitz/build` for the above use case.

### Additional context

After docker run:
![image](https://user-images.githubusercontent.com/8077469/118475336-08c7dc00-b704-11eb-9226-604020c5ffbf.png)

**Comment by flybayer** [comment]
Makes sense!

We put blitz.config.js in `.blitz/` because we need the config before `.blitz/build/` is created.

The custom server could go inside `.blitz/build/` but that folder will go away once the next.js fork migration is complete. Which is why I put it just inside `.blitz/`.

### Implementation as I'm seeing it

1. Skip the build config step if command is `blitz start` here: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/index.ts#L13
2. Extract build code from `startCustomServer` into a new `buildCustomServer` function in https://github.com/blitz-js/blitz/blob/canary/packages/server/src/next-utils.ts#L247 (so startCustomServer will not build unless watch:true
3. Change `blitz dev` to run `buildCustomServer` and `startCustomServer` here: https://github.com/blitz-js/blitz/blob/canary/packages/server/src/dev.ts#L43-L44
4. Run `buildCustomServer` on this line: https://github.com/blitz-js/blitz/blob/canary/packages/server/src/build.ts#L39

**Comment by mabadir** [comment]
Hey all, I am picking up this issue, and will work on it.
