### ISSUE TITLE
Add custom templates support

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#236]
**What do you want and why do you want it?.**

Blitz comes with default templates for `blitz generate`. This is a feature that seems really cool to start with but very quickly becomes just a toy because you can't use it in real projects. This was the downfall of `rails generate`. 

However, `blitz generate` can be super useful throughout the entire life of a project if we have an easy way to eject templates and let users customize them.

It's not in scope of this issue, but we'll also have ability for users or plugins to add generators to the `blitz generate` command.

**Implementation**

I don't really have any thoughts about this at the moment, except that I think we should probably eject to `/templates/*`.

I'd love if someone can think about how this should all work and then post a proposal here.

**Comment by aem** [comment]
Ok I've done some thinking and here's how I'd like to go about this:

1. Add a new, meta `blitz generate template [type] [name]` command. It'll accept the same `type`s as `blitz generate`, and will generate a template called `[name]` in `/templates/[name]`, with files copied directly from our existing templates. From there, the user can modify the template however they want. These templates should also have some method of getting values into the template, maybe via a `.getTemplateValues.ts` that lives at the root of the template. We can enforce this file supplies the values needed to conform to the `Generator`'s interface.
2. Update `blitz generate [type] [name]` to also look for `[type]`s in `/templates/*`. Since we can read these values from the filesystem during CLI startup, we could even include these template values in the help menu for `blitz generate`. We'll coalesce the methods/fields provided in `.getTemplateValues.ts` with the abstract `Generator` class to dynamically create a generator and place its files where instructed based on the CLI command, just like a normal `generate` invocation.

**Comment by flybayer** [comment]
Nice!

- Can we use "eject" since folks are so common with that
	- So like  `blitz generate eject ...args` 
- Why do we need both `type` and `name`?
- Are we ejecting the actual generator class too or only the template? I was initially thinking the later, but I think we should do the former. Then users can even create totally new generators like `component` for example. So like `blitz generate generator component`

**Comment by ryardley** [comment]
Awesome feature idea but personally I would question if "eject" is the best terminology here. Eject to me feels like a permanent change where I as a dev have no further use for the cli since everything is now available as a script that I can fully customize.  Would "custom generators" be a better way to describe the feature?

**Comment by flybayer** [comment]
Even if we make it clear you are "ejecting a template" (or generator) instead of "ejecting blitz cli"?

This would be on a doc page under advanced generator usage. So I don't think it would be confusing.

**Comment by aem** [comment]
> Why do we need both type and name?

The `type` arg is to choose which Blitz template to base the new template from. However, we'd also need to give the new template a custom name - if we give it the same name that we use for our templates then there's no way to access the old template anymore. I think it's probably pretty likely that the user would want to, say, create a few different `page` templates based on different segments of their app. That's hard to do if they have to manually rename the template every time they create a new one.

> Are we ejecting the actual generator class too or only the template?

I think we should start with just the template and then see what people ask us for. I'd be hesitant to slow down v1 of ejected templates to support custom generator classes just to find out people don't really need it. In particular I think that feature isn't super helpful until #232 and #233 are completed

> I would question if "eject" is the best terminology here

I kind of agree on this. In most other cases (e.g. `create-react-app`) `eject` means "you're leaving the framework and you're on your own now" which is definitely not true in this case. The original template will still exist (unless you create a new one named `page`, etc) and your template is still a direct hook into the framework, so it's not a true `eject`ion which is why I went with `blitz generate template`. Open to other suggestions though

**Comment by beerose** [comment]
If someone wants to work on that, there's been an initial work done in this PR: https://github.com/blitz-js/blitz/pull/1018, which might be good for a starting point or an inspiration for future work.
