### ISSUE TITLE
Enable stack trace in db/seeds.ts

### ISSUE THREAD

**Issue by thangngoc89** [blitz-js/blitz#2486]
### What do you want and why?

I like the nice out put when running `blitz db seed` but it hides all stack traces and makes it very difficult to know where does the error originated.

### Possible implementation(s)

I'm not sure

### Additional context

![image](https://user-images.githubusercontent.com/3049054/121925047-b4e1fe80-cd66-11eb-8198-01ef81b7f620.png)

**Comment by flybayer** [comment]
Thanks for the bug report!

This should be a simple fix:

Change this line: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/db.ts#L36
and this line: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/db.ts#L82

to use `baseLogger.error` instead of `log.error`.

Import baseLogger like this:

```ts
import {log, baseLogger} from "@blitzjs/display"
```

**Comment by koolii** [comment]
@flybayer Hi, can I tackle this issue?

**Comment by flybayer** [comment]
@koolii yes!!
