### ISSUE TITLE
Warning after redirectAuthenticatedTo

### ISSUE THREAD

**Issue by medihack** [blitz-js/blitz#2595]
### What is the problem?

After redirection because of `redirectAuthenticatedTo` the below warning occurs in the console.

### Paste all your error logs here:

```
`Warning: An error occurred during hydration. The server HTML was replaced with client content in <div>.`
```

### Paste all relevant code snippets here:

None.

### What are detailed steps to reproduce this?

1. Create a new project
2. Login
3. Visit `localhost:3000/login`

### Run `blitz -v` and paste the output here:

```
blitz: 0.38.6 (global)
blitz: 0.38.6 (local)

  Package manager: yarn 
  System:
    OS: Linux 5.10 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 8.50 GB / 12.42 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.2 - ~/.nvm/versions/node/v14.17.2/bin/node
    Yarn: 1.22.10 - /mnt/c/Users/kaisc/AppData/Roaming/npm/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.2/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.27.0 => 2.27.0 
    blitz: 0.38.6 => 0.38.6 
    prisma: 2.27.0 => 2.27.0 
    react: alpha => 18.0.0-alpha-c76e4dbbc-20210722 
    react-dom: alpha => 18.0.0-alpha-c76e4dbbc-20210722 
    typescript: ~4.3 => 4.3.5
```

**Comment by flybayer** [comment]
This is expected because our redirects are implemented via `throw` inside the render function. This is necessary to prevent the user from seeing something they shouldn't. In the case of redirectAuthenticated, it's probably not a big deal. But it's important for redirecting unauthenticated users.

My opinion is that React should not log that warning in the case when errors are thrown, because this is expected.

**Comment by medihack** [comment]
Ok, good to know. Then let's close the issue. At least it is now documented somewhere.
