### ISSUE TITLE
Hide meta property when calling a query via Postman/External Tool

### ISSUE THREAD

**Issue by noxify** [blitz-js/blitz#2683]
### What do you want and why?

**What:**
When using the auto-generated api endpoints to call them via an external tool ( e.g. postman or a 3rd-party application ),
the response includes always a `meta` property.

The content is something like this:
( i have two date fields in the enviroments table )

```
 "meta": {
   "result": {
     "values": {
       "environments.0.createdAt": [
         "Date"
       ],
       "environments.0.updatedAt": [
         "Date"
       ],
       "environments.1.createdAt": [
         "Date"
       ],
       "environments.1.updatedAt": [
         "Date"
       ],
       //...
     }
   }
 }
```
It would be good if there is a way to hide it - or if not needed, we could remove it.

**Why:**

It reduces the size from the response body, which results in a better performance 🚀

In my test with 100 records, i was able to reduce the size from 58kb to 44kb ( on my local storage ).

### Possible implementation(s)

How might we do this?

Currently I'm not sure how to implement it, because I'm not sure if the meta is generated from blitz or something else ( e.g. react-query?! )

---

The issue/feature is based on the discussion last week in discord: https://discord.com/channels/802917734999523368/870041934046060615/878704678429425705

**Comment by flybayer** [comment]
Thanks @noxify!

My proposal is to accept a new header. If the header is present, we skip the superjson step.

```
Headers:
blitz-disable-superjson: true
```

Thoughts?

**Comment by MrLeebo** [comment]
@noxify the meta attribute is generated to serialize values to the same type client-side as they had server-side. So when your query returns a Date value, you get a Date in your react component instead of a string.

@flybayer if there's going to be header override like that, I think the RPC handler should check to see if the header has been added (for instance, via global middleware) and remove it / log a warning so future people don't accidentally break their apps if they mistake this snippet as some kind of "performance hack"
