### ISSUE TITLE
Auto load application code into the blitz console REPL

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#27]
As much application code as makes sense should be auto loaded into scope, such as models, controllers, integration files, utils, and jobs.

This is pending the file structure being nailed down a bit more.

**Comment by quirk0o** [comment]
when this gets started I have some thoughts and research on this that I could share :)

**Comment by quirk0o** [comment]
Would we want to autoload dependencies (node_modules) as well? I'm thinking that would make a lot of sense

**Comment by flybayer** [comment]
@quirk0o you're welcome to go ahead and post it all here now! Might as well start discussion on what this will look like exactly.

**Comment by quirk0o** [comment]
Sure!
So if we're using the builtin Node REPL module (which I haven't found any alternative to) then here are some thoughts:
* we can use the repl's `context` property to assign any variables to the global scope in the repl
* I created a POC for loading the project's dependencies in here https://github.com/blitz-js/blitz/compare/canary...quirk0o:cli/feature/console-load-deps?expand=1
* it's important to invalidate the require cache when reloading modules otherwise we'd always get the first version
* it could be worth thinking about saving the repl history later on (https://medium.com/@tjwebb/a-custom-node-repl-with-history-is-not-as-hard-as-it-looks-3eb2ca7ec0bd)
* when it comes to loading app modules I'm thinking just using `globby` or similar should be straightforward and good enough ? (but it would have to depend heavily on the file structure that we go with)

I'm wondering whether the autoloading feature should really rely so much on the file structure? I mean, we would have some definite requirements but nothing would prevent the developer of creating e.g. an additional folder in the root directory.

**Comment by ryardley** [comment]
I think having access to the prisma client will be helpful esp with autocomplete.

**Comment by flybayer** [comment]
Good points @quirk0o!

- Let's use a file watcher to auto reload packages in the REPL. Rails requires you to run `reload` which is quite annoying
- Yes, definitely add a command history! I use this all the time in rails
- Definitely add a prisma client instance

P.s. You should have write access to this repo, so you don't have to use your fork. You can create new branches in this repo.

**Comment by quirk0o** [comment]
@flybayer would you like me to create a PR with these changes?

**Comment by flybayer** [comment]
@quirk0o sure!

**Comment by flybayer** [comment]
Related #116

**Comment by simonpeterdebbarma** [comment]
@flybayer I think we can close this issue as it's been resolved.
