### ISSUE TITLE
Mutation / Query Mocking utilities

### ISSUE THREAD

**Issue by Skn0tt** [blitz-js/blitz#280]
### What do you want and why?

Commonly, API calls will be mocked out in tests in order to decouple and speed them up.
Since one of Blitz core concepts is to hide network calls and replace them by (opaque) RPC, the natural counterpart would be to just mock out the generated network fetching logic instead.

The interface could look like this:

```ts
import ProjectsList from "./ProjectsList";
import getProjects from "./queries/getProjects";
import { mockQuery } from "blitz/test";

const getProjectsMock = mockQuery(
  getProjects,
  // mock implementation
  async () => {
    return [{ id: 1, name: "Blitz" }];
  } 
);

describe("ProjectsList", () => {
  it("calls `getProjects`", () => {
    const comp = render(() => <ProjectsList />);
    expect(getProjects).toHaveBeenCalled();
  })
})
```

### Possible implementation(s)

Since Blitz already replaces queries with generated code, we could just generate a "sleeping mock" during testing.
By "Sleeping", i mean: mocking would be disabled by default, but could be enabled using `mockQuery`.

This would circumvent all Test-Runner mocking mechanisms and thus doesn't run into the problem of mocks needing to be hoisted (see Jest hoisting jest.mock).

**Comment by aem** [comment]
Do we need this? Couldn't we just mock the `getProjects` fn in that example?

**Comment by Skn0tt** [comment]
You've got a point there -  I should've explained why simply running `jest.mock` isn't sufficient 😅

So the problem is that the useQuery hook [requires a cache key](https://github.com/tannerlinsley/react-query#queries), which is hidden away [in Blitz' code generation](https://github.com/blitz-js/blitz/search?q=cacheKey).

When mocking `getProjects`, you'd need to assign that cache key:

```ts
import getProjects from "./queries/getProjects";

async function mockImplementation() {
   return [{ id: 1, name: "Blitz" }];
}

mockImplementation.cacheKey = "mockImplementation";

jest.mock("./queries/getProjects", () => mockImplementation);

// ...
```

Since the cacheKey is a code gen implementation detail that should be hidden away from the user, a helper function could be provided from Blitz:

```ts
// blitz/test
export function createQueryMock<T extends Function>(mockImplementation: T) {
  mockImplementation.cacheKey = mockImplementation.name; // alternatively: some random, but stable name
  return mockImplementation;
}
```

```ts
import getProjects from "./queries/getProjects";
import { createQueryMock } from "blitz/test";

jest.mock(
  "./queries/getProjects",
  () => createQueryMock(async () => {
    return [{ id: 1, name: "Blitz" }];
  })
);

// ...
```

There's just one Problem with this: Since jest.mock calls are hoisted (see above), making createQueryMock available would require some kind of Babel/Webpack trickery.

There's one possible fix that came to my mind: [Using `queryFn.cacheKey ?? queryFn.name` as the cache key](https://github.com/blitz-js/blitz/blob/5da2eae6e13e30a161c72e8c2854397fd026ef3b/packages/core/src/useQuery.ts#L25). But I don't really know about the uniqueness guarantees required for cacheKey / given by `Function#name`, so maybe that's a good idea, maybe it isn't.

**Comment by ryardley** [comment]
What level of testing are you suggesting this is for?

**Comment by Skn0tt** [comment]
Mostly integration testing. It would allow you to test behaviour of your components and assert on the neccessary calls being made.

**Comment by aem** [comment]
Jest mocking shouldn't require a mock cache key, the call should never hit the underlying implementation which means the cache key should be irrelevant 🤔 unless I'm reading this wrong

**Comment by Skn0tt** [comment]
The cache key is not a required part of the implementation, but solely to make it work with react-query. Testing components would hit react-query implementation, so that's why it's relevant.

**Comment by ryardley** [comment]
I get why you might want that but I am not sure that testing at that level makes a whole lot of sense honestly. Testing your backend talks to your frontend should probably be done with cypress. The cache key stuff will likely go through a lot of churn soon so anything we do here would need to be changed too. You still have standard jest based react-testing-library for pages and can simply use jest to mock out return values for queries and mutations using the require hooks jest provides.

**Comment by Skn0tt** [comment]
Well that's exactly the problem here: Mocking out return values for queries isn't easily possible, as the recommended way (`useQuery(myFunnyQuery)`) requires that cache key to be present in mocks - or am I missing something here? Actually, failing to test using `react-testing-library` and `jest.mock` is what inspired this issue in the first place.

**Comment by ryardley** [comment]
Ahh ok I see. Sounds to me like we should just have useQuery simply call the resolver function it is passed when it is being tested in jest as the backend won't be available.

**Comment by Skn0tt** [comment]
So like this ...

```ts
function useQuery(resolver) {
  if (isTestMode) {
    return [ resolver(), reactQuerySecondReturnValueMock ];
  }
  ...
}
```

(has the problem of not resembling react-query characteristics, which makes tests less useful)

... or like this ...

```ts
import { useQuery as useReactQuery } from "react-query";

function useQuery(resolver) {
  if (isTestMode) {
    return useReactQuery([ resolver.name ], resolver);
  }
  ...
}
```

(has the problem of the cache key, `resolver.name` in this case, being potentially duplicated, which could clash with its query cache)

... or some totally different way? Is there an option I'm missing here?

**Comment by jan-wilhelm** [comment]
Is there any update on this? I still find integration testing quite hard with Blitz. Any RFC / issues / PR somebody could point me to to leave my thoughts on?

**Comment by flybayer** [comment]
@jan-wilhelm the only thing we have so far is [this default test file](https://github.com/blitz-js/blitz/blob/canary/packages/generator/templates/app/app/pages/index.test.tsx) we include in new apps by default that shows how to mock a shared hook.

**Comment by JoseRFelix** [comment]
I recommend using [Mock Service Worker](https://github.com/mswjs/msw) to mock the requests at the network level using service workers. It is really easy to learn and use, and it lives separate from your code which makes it more readable. Check it out!

By the way, testing if a query or mutation is called is considered an implementation detail. I'm generally against it. Here is a really good [article](https://kentcdodds.com/blog/testing-implementation-details) from Kent C. Dodds that explains why.

**Comment by MrLeebo** [comment]
I agree with @JoseRFelix about MSW being a good approach for this. It would be cool if we had a blitz wrapper around MSW for handling RPC calls without having to calculate their URLs:

```js
import { rpc } from '@blitz/test';
import { setupServer } from 'msw/node';
import getUsers from 'app/users/queries/getUsers';

const server = setupServer(rpc(getUsers, (req, res, ctx) => { ... }));
```

**Comment by reggie3** [comment]
Has anyone had any success getting Mock Service Worker working so far?

I'm trying to set up basic MSW integration with blitz for testing and am receiving this error when running my test.

```
TypeError: Cannot read property '$authorize' of undefined
        at _innerAuthorize (C:\Users\rej_i\OneDrive\Development\blitz-quiz-app\node_modules\@blitzjs\core\server\dist\blitzjs-core-server.cjs.dev.js:377:13)
        at C:\Users\rej_i\OneDrive\Development\blitz-quiz-app\node_modules\@blitzjs\core\server\dist\blitzjs-core-server.cjs.dev.js:358:26
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by flybayer** [comment]
@reggie3 I haven't used MSW, but my understanding is that when MSW makes it easier to test your frontend by removing any calls to backend code, right?

If that's true, then the issue you are showing is that backend code is still being called. Probably because you are importing the query or mutation and passing to useQuery. But in our build, we replace that import with a tiny http client. So by default with code as it's written, there is no http calls. You first have to replace the server function import with an http client.

It might be possible to add some MSW support directly to our useQuery hook that would automatically do that swap in a MSW environment 🤔

**Comment by reggie3** [comment]
@flybayer Thanks for the quick response.

 With MSW, an API call is still made by the client, but the call is intercepted by MSW which responds with whatever is specified in the configuration give to MSW.  So the backend call isn't removed, just intercepted before it gets to the actual server.

**Comment by flybayer** [comment]
Ok, so in your case MSW is not doing anything, because there's no network request. The resolver is being called directly. If MSW was intercepting a network request, then that resolver function would not be called.

Here's [the rpc client](https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/data-client/rpc.ts#L74-L243) that we replace the function import with.

Maybe let's take a step back, what's the end goal you are trying to accomplish here?

**Comment by reggie3** [comment]
Thanks for the info on the rpc client. 

1. I'm trying to run a React Testing Library test that types text into an input and clicks a submit button. 
2. The submit button makes an async call to a mutation.
3. When the program is run in dev, the mutation returns an object based on the response from the server.  Since this is a test, I want to specify the response that is returned.
4. A successful object return should result in a new component with some of that objects information being added to the list which I can make an assertion on in the test.

I guess the bottom line is that I need a way to specify what the mutation returns.  

This is in line with the prior conversations in this thread, and MSW was one of the techniques mentioned as a potential solution.

**Comment by flybayer** [comment]
@reggie3 ok understood, Then I think by far the easiest way is to mock your createAnswer mutation with jest, like mocking any old function. No network involved.

**Comment by reggie3** [comment]
Seems like I'll run into the same problems @Skn0tt ran into previously if I try it that way, but I'll give it a shot.

**Comment by reggie3** [comment]
@flybayer Once again thanks for all the help so far.  I do have another question.  When you said:

 "Ok, so in your case MSW is not doing anything, because there's no network request. The resolver is being called directly. If MSW was intercepting a network request, then that resolver function would not be called."

How is the resolver is being called directly?  The documentation for Mutation Resolvers states "Blitz mutations are plain, asynchronous JavaScript functions that always run on the server."  

I verified my MSW setup works when calling the Star Wars API so that's not an issue.  Is there something about testing that prevents the generated code from attempting to call APIs?

**Comment by flybayer** [comment]
Here's the babel plugin that replaces the resolver file contents in the client build: https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/build/babel/plugins/blitz-rpc-client.ts

And here's the babel plugin that modifies the resolver file contents in the server build: https://github.com/blitz-js/blitz/blob/canary/nextjs/packages/next/build/babel/plugins/blitz-rpc-server-transform.ts
