### ISSUE TITLE
Readme.md at every folder level

### ISSUE THREAD

**Issue by kandros** [blitz-js/blitz#318]
A `readme.md` in every package (folders in`/packages`) explaining what the package does and why it exists would greatly increase the ability to navigate the codebase for newcomers and make sure there is no abstraction leaks from one package to another

## important points
- what the package does 
- how it fits in the whole Blitz architecture
- how to work on it locally if it requires special setup
- what the package does not (sometime this is useful)

**Comment by agnelnieves** [comment]
I would love to work on this

**Comment by flybayer** [comment]
Very nice @kandros — I was going to open an issue for this.

I'm also adding to this, that we should have a Readme.md in almost every folder explaining everything at that level.

**Note:** Do not put a README.md at `packages/blitz/README.md` because that will be clobbered by the NPM release process which temporarily copies the root readme to that location for publishing to npm. However, it could still have a readme but just with a slightly different name.

@agnelnieves that'd be great! You can open a PR for this. You don't have to add all the READMEs in one PR. Just do what you think you can. Someone else can do another PR adding what's missing.

**Comment by LoriKarikari** [comment]
Hi, @agnelnieves any updates on this?
