### ISSUE TITLE
Migrate `env-config-app-env` integration test

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3223]
https://github.com/blitz-js/blitz/tree/canary/nextjs/test/integration/env-config-app-env

**Comment by JoelLau** [comment]
hi @flybayer , i would like to pick this issue up as part of `hacktoberfest` if it's okay with you. Do you mind elaborating on what is expected of the integration test?

**Comment by beerose** [comment]
@JoelLau, here's the integration test directory that needs to be migrated: https://github.com/blitz-js/legacy-framework/tree/main/nextjs/test/integration/env-config-app-env. You should add it to this project's `integration-tests` folder and modify it accordingly (we use vitest now instead of jest). You can follow other tests in `integration-tests` to see how to make the changes. 

Also, I'm assigning you to this issue. Let us know if you face and issues or if you have additional questions.

**Comment by JoelLau** [comment]
had some trouble installing pnpm, but its working now! i'm still working on this - hope to open a PR in the coming week. will post questions here 

_(sorry for the delay)_
