### ISSUE TITLE
Building store example fails on Windows

### ISSUE THREAD

**Issue by wKovacs64** [blitz-js/blitz#353]
### What is the problem?

Maybe the relative synchronizer rule is normalizing import paths when it shouldn't? Not sure yet.

### Steps to Reproduce: 

1. Clone Blitz repo on Windows
1. Either run the tests, or cd into `examples/store` and try to build the store example
1. Observe `Bad character escape sequence` error

### Versions:

```
debug: monorepo
debug: pkgPath: C:\dev\contrib\blitz\node_modules\@blitzjs\cli

Windows 10 | win32-x64 | Node: v12.16.1

blitz: 0.7.0 (global)
blitz: 0.7.1-canary.1 (local)
```

### Supporting Documentation:

```
Creating an optimized production build

Failed to compile.

./app/products/components/ProductForm.tsx
SyntaxError: C:\dev\contrib\blitz\examples\store\.blitz\caches\build\app\products\components\ProductForm.tsx: Bad character escape sequence (4:51)

  2 | import {Product, ProductCreateInput, ProductUpdateInput} from 'db'
  3 | import createProduct from 'app\products\mutations\createProduct'
> 4 | import updateProduct from 'app\products\mutations\updateProduct'
    |                                                    ^
  5 |
  6 | type ProductInput = ProductCreateInput | ProductUpdateInput
  7 |


> Build error occurred
```

Blitz code (`examples\store\app\products\components\ProductForm.tsx`):

```ts
import createProduct from '../mutations/createProduct'
import updateProduct from '../mutations/updateProduct'
```

Compiled code (`examples\store\.blitz\caches\build\app\products\components\ProductForm.tsx`):

```ts
import createProduct from 'app\products\mutations\createProduct'
import updateProduct from 'app\products\mutations\updateProduct'
```

The resulting backslashes are incorrect, they should remain forward slashes (in code).

### Note:

I don't seem to run into this in a newly generated project, but we're still getting the issue reported in #299 so we might just not be making it that far yet? 🤔

**Comment by Jfelix61** [comment]
#### Problem
After some investigation, the [`relativeToAbsolute`](https://github.com/blitz-js/blitz/blob/99b4cd628c25a6d647a33e0bcaf249e2a11f6da6/packages/server/src/synchronizer/pipeline/rules/relative/index.ts#L42) function is the culprit. `path.sep`, `process.cwd()` and the file's paths are being returned with back slashes.

[`relative-paths.test.ts`](https://github.com/blitz-js/blitz/blob/99b4cd628c25a6d647a33e0bcaf249e2a11f6da6/packages/server/src/synchronizer/pipeline/rules/relative/relative-paths.test.ts)'s tests are giving a false positive since the `path.normalize` function replaces forward slashes with back slashes.

#### Possible Solution

Out of my I can think of avoiding normalizing the paths in test, and replace any back slash with forward slash in [`relativeToAbsolute`](https://github.com/blitz-js/blitz/blob/99b4cd628c25a6d647a33e0bcaf249e2a11f6da6/packages/server/src/synchronizer/pipeline/rules/relative/index.ts#L42) using `replace`. However, I don't yet know the extent of this function in the codebase. Perhaps it would be a better idea to transform on stream's input.

#### Additional Resources 

Here is a screenshot of test with some debugging messages on Windows 10: 

![image](https://user-images.githubusercontent.com/21092519/80778505-a15ddf00-8b36-11ea-82fc-104920b36190.png)
