### ISSUE TITLE
Add `zod` as one of the dependencies we print in `blitz -v`

### ISSUE THREAD

**Issue by Zeko369** [blitz-js/blitz#3660]
### What do you want and why?

It would be useful to also print the `zod` version (since a mismatch / outdated zod can cause a bunch of problems)

### Possible implementation(s)

In [index.ts:88](https://github.com/blitz-js/blitz/blob/f60f96f5d1412b6c810b1d5e94d8dda5b6ee5454/packages/blitz/src/cli/index.ts#L89), add `zod` as the last element in array

**Comment by chaiwattsw** [comment]
Hi, I would like to take this issue

**Comment by beerose** [comment]
Hmm, `zod` is not a core element of Blitz, and in my opinion, it's one of the things that can be super easily removed and replaced. I'm not very fond of adding it to the list. Because if we do it with `zod`, then why not do it for jest, eslint, ts-node? The fact that it was causing issues is on us, and we should make sure to fix the root cause and talk about it to inform users what to do etc.
