### ISSUE TITLE
`blitz` takes too long to install

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#377]
### What is the problem?

`yarn global add blitz` or `npm i -g blitz` takes a long time, presumably because we have so many dependencies.

We need to see how we can optimize this. Do we have some really heavy dependencies that swap out with something else? Or maybe we are only using one small part of a large dependency that we can inline into our code?

### Versions:

```
macOS Catalina | darwin-x64 | Node: v12.16.2

blitz: 0.7.0 (global)
```

**Comment by Skn0tt** [comment]
I'll have a look at this.

**Comment by Skn0tt** [comment]
If install time is a key metric we're focusing on, we should think about having some kind of hard limits on file size that we enforce as part of our CI.

**Comment by Skn0tt** [comment]
Judging from [this](https://arve0.github.io/npm-download-size/#blitz), Next.js makes up 90% of our dependency size (14mb total, 12mb of that is Next.js).

**Comment by Skn0tt** [comment]
## Some totally non-scientific measurements:

In a clean environment (`docker run node:12.16`), `yarn global add blitz` finishes in 42s and fetches 950 different packages. For me, it finishes in 40secs.

On my host system, where there's already lots of dependencies installed globally, it fetches ~2400 different packages and finishes in 60secs. A lot of this time is spent "building fresh packages", which seems to be a common problem with globally installed packages.

`yarn list --flat --prod | wc -l` counts ~2900 individual dependencies to be installed. Maybe the high number of individual packages contributes to slow install time.

---

We'd need to find some consensus on what "a long time" means to us. For me personally, 30secs is more than alright, the 60secs get on my nerves - but mostly because "building fresh packages" takes soooo long without any substantial progress.
How long does installing take for you @flybayer ?

**Comment by LoriKarikari** [comment]
Here the installation takes 32s. Seems not too bad?

**Comment by wKovacs64** [comment]
blitz@0.8.1 took 13s on my Windows host machine (most/all dependencies probably cached) and 42s in a VM with no cached dependencies. Off the cuff, I think I agree with Simon's thresholds: <30s is great, ~45s is fine, >=60s is starting to get irritating.

**Comment by Skn0tt** [comment]
We could add a CI check to enforce those thresholds. @flybayer what do you think?

**Comment by flybayer** [comment]
Ok cool, if Next is the large majority then that's really good. I wanted to make sure we weren't adding a ton ourselves.

It would be nice to have some type of CI check for this. We also want to test the client bundle size via CI at some point.

**Comment by Skn0tt** [comment]
I'll work on a CI check :D
