### ISSUE TITLE
Strategy for CSRF protection to work with SSE or be individually disabled

### ISSUE THREAD

**Issue by tmcw** [blitz-js/blitz#3789]
### What do you want and why?

My application currently uses Server-Sent-Events as part of a realtime collaboration system. It's not possible to [set headers using SSE](https://github.com/whatwg/html/issues/2177) at the browser level.

This breaks CSRF, which relies on setting the csrf token as a request header.

Given this limitation, it would be nice to:

- Specify the token another way
- Disable CSRF on a per-request basis
- Or another option that I'm not thinking of

### Possible implementation(s)

At the moment, something like

```js
getSession(req, res, { disableCSRF: true })
```

Would work for me.

**Comment by dillonraphael** [comment]
Ah I see what you mean. @flybayer any thoughts on this?

**Comment by flybayer** [comment]
Yes we can add ability to turn off CSRF, either with getSession as suggested and/or as a global config. Turning it off is fine as long as the session sameSite config is set to "strict" or "lax" (default), since same site cookies prevent cross site scripting attacks as long as mutations are not made with GET requests.

**Comment by MrLeebo** [comment]
Seems worthwhile to allow csrf tokens to be read from FormData because SSE isn't the only context where you may not have the ability to set headers
