### ISSUE TITLE
Autoload path (import and export)

### ISSUE THREAD

**Issue by devaayushraj** [blitz-js/blitz#3854]
In a normal JS program, dependencies need to be loaded by hand. (import and export)

This shouldn't be case within a framework. 

Instead of: 

```
import { resolver } from "@blitzjs/rpc"
import db from "db"
import * as z from "zod"

export const CreateProject = z
  .object({
    name: z.string(),
  })

export default resolver.pipe(

  resolver.zod(CreateProject),

  resolver.authorize(),

  async (input) => {
    const project = await db.project.create({ data: input })
    return project
  }
)

```
We should be doing this:

```
const CreateProject = zod
  .object({
    name: z.string(),
  })

 resolver.pipe( 
  resolver.zod(CreateProject), 
  resolver.authorize(),
  async (input) => {
    const project = await db.project.create({ data: input })
    return project
  }
)

```
Point of a framework is to make our life easier, isn't it?

**Comment by beerose** [comment]
Blitz is a JavaScript framework, so you do have to write a valid JavaScript or TypeScript code. Being a framework means abstracting boilerplate and providing solutions that would otherwise require users to write a lot of code. Yet as long as it's a JavaScript framework, it will require JavaScript syntax.
