### ISSUE TITLE
`PORT` is not forwarded to `next start`

### ISSUE THREAD

**Issue by pestaa** [blitz-js/blitz#3949]
### What is the problem?

`PORT` is not forwarded to `next start`.

### Paste all your error logs here:

```
$ PORT=8080 node_modules/.bin/blitz start
Loaded env from /srv/www/.env
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
```

vs

```
$ PORT=8080 node_modules/.bin/next start
ready - started server on 0.0.0.0:8080, url: http://localhost:8080
info  - Loaded env from /srv/www/.env
```

### Paste all relevant code snippets here:

-

### What are detailed steps to reproduce this?

-

### Run `blitz -v` and paste the output here:

Blitz version: 2.0.0-beta.14 (local)

**Comment by flybayer** [comment]
@pestaa thanks for reporting this! Want to take a stab at fixing it? Here's the line of code where you need to add PORT awareness: https://github.com/blitz-js/blitz/blob/main/packages/blitz/src/cli/utils/next-utils.ts#L158

**Comment by nkilm** [comment]
@flybayer I would like to work on this issue.

**Comment by nkilm** [comment]
@flybayer Please correct me if I am wrong, this is order of flow
1. Execution starts from `/src/cli/index.ts` - [this line](https://github.com/blitz-js/blitz/blob/916692db74bee043cb5992500e052bea9152cb5e/packages/blitz/src/cli/index.ts#L30)
2. Then this calls the function `dev()` present in `/src/cli/commands/next/dev.ts`. - [this line](https://github.com/blitz-js/blitz/blob/916692db74bee043cb5992500e052bea9152cb5e/packages/blitz/src/cli/commands/next/dev.ts#L22)
3. Later `dev()` inside `/src/cli/utils/next-commands.ts` is called. -[this line](https://github.com/blitz-js/blitz/blob/916692db74bee043cb5992500e052bea9152cb5e/packages/blitz/src/cli/utils/next-commands.ts#L22)

I don't see any problem here, `port` should be passed without any errors.

**Comment by nkilm** [comment]
@pestaa Okay

**Comment by flybayer** [comment]
@nkilm some context: nextjs used to always use port 3000 even if something else was using it. So in blitz we auto detected next available port and used that.

But now nextjs does the autodetection, so we should remove all the availablePort stuff from our code. Then PORT will work as expected.

I forgot this nextjs port change earlier which is why I'm just now mentioning it :)

**Comment by nkilm** [comment]
@flybayer Since nextjs does autodetection for PORT, there is no need to add `fallback PORT(3000)` to blitz-js?

If yes then this condition checking should be removed - https://github.com/blitz-js/blitz/blob/936211a657202aab4ba68791eb2f2aefa02db590/packages/blitz/src/cli/utils/next-utils.ts?rgh-link-date=2022-11-06T03%3A44%3A55Z#L158

**Comment by flybayer** [comment]
@nkilm correct, we can remove this line

**Comment by nkilm** [comment]
@flybayer Okay, will open PR asap.
