### ISSUE TITLE
add blitz generate command

### ISSUE THREAD

**Issue by marcoseoane** [blitz-js/blitz#40]

**Comment by tsawan** [comment]
@flybayer any details here then I might be able to pick it up?

**Comment by flybayer** [comment]
@tsawan it's already mostly done in #46

**Comment by flybayer** [comment]
Ok @marcoseoane! Here's the details for the generate command. For now it's only one generator command.

Are you able to work on this soon? If not, we can label "help wanted" until someone else (or you) is able to do it.

---

Goal: a single command to generate **working** crud code for a model. Then you can customize from there. At some point we'll add ability to define the templates inside a blitz app, so that an app can have custom templates.

```
blitz generate crud [context/]MODEL(s)
```

Model input can be singular or plural. The result is the same.

```
blitz generate crud project
blitz generate crud projects
```

The above commands will both generate the following:

```
app/projects/queries/getProject.ts
app/projects/queries/getProjects.ts
app/projects/mutations/createProject.ts
app/projects/mutations/updateProject.ts
app/projects/mutations/deleteProject.ts
app/projects/components/ProjectForm.ts
app/projects/pages/projects/index.ts
app/projects/pages/projects/new.ts
app/projects/pages/projects/[id].ts
app/projects/pages/projects/[id]/edit.ts
```


Once we figure out the testing system, we'll also generate working tests.

The content of all those files can be roughly what's in the store example. I'm not sure what to do for the form component yet. How we should handle a form library. I think to start, we shouldn't use a form library, and just have some vanilla JS that does the job.

**Comment by marcoseoane** [comment]
Hey! Yeah sure I'll get to work on having this completed for this week thurs/fri?, by all means put up a help wanted in case theres an extra eager contributor laying in wait for a ticket :)

**Comment by flybayer** [comment]
Ok sounds great!!

**Comment by flybayer** [comment]
So I'd also like to add an optional `--parent MODEL` argument:

```
blitz generate crud task --parent project
```

Would generate the following:

```
app/tasks/queries/getTask.ts
app/tasks/queries/getTasks.ts
app/tasks/mutations/createTask.ts
app/tasks/mutations/updateTask.ts
app/tasks/mutations/deleteTask.ts
app/tasks/components/TaskForm.ts
app/tasks/pages/projects/[projectId]/tasks/index.ts
app/tasks/pages/projects/[projectId]/tasks/new.ts
app/tasks/pages/projects/[projectId]/tasks/[id].ts
app/tasks/pages/projects/[projectId]/tasks/[id]/edit.ts
```

Building all of this is a lot of work, so feel free to split them up into different PRs. For example, the first PR could support generating queries/mutations, but not not the pages.

**Comment by flybayer** [comment]
Hey @marcoseoane, could you share a quick status update on this and if you've started or not?

**Comment by flybayer** [comment]
We need this for the alpha release, so if noone else can get to this within the next day or two, I'll do it.

**Comment by aem** [comment]
Talked with @flybayer in Slack, I'm going to pick up the generator this week. Should be manageable given the existing scaffolding for `new` to leverage the existing infrastructure to implement the rest of `generate`

**Comment by aem** [comment]
Is the terminology `crud` set in stone. How would we feel about a novel term that's specific to Blitz. Maybe a "resource" - e.g. allowing us to talk about this set of files/components like this:

> A Blitz Resource represents the collection of objects that enable CRUD operations for a data set. A Resource comprises queries, mutations, components, and pages. This set of files, collectively referred to as a Resource, makes up a full data flow, from front to back, of a data model. It supplies a page in the UI, display components, RPCs to operate on the data, and the backing prisma models in the database.

It has the benefit of our CLI reading slightly more like English - `blitz generate resource task`

**Comment by flybayer** [comment]
That's a good question.

So here's the main generation use cases I expect:

- Generates only the schema definition (like `blitz generate model User name:string`)
- Generates only queries/mutations
- Generates only pages and/or components
- Generates everything

We should probably go ahead and figure out what the naming will be for all of these.

I'll think about this and circle back tomorrow.
