### ISSUE TITLE
`message` in form Error object is not deserialized

### ISSUE THREAD

**Issue by tordans** [blitz-js/blitz#4059]
### What is the problem?

When I create a from (eg `pages/projects/new.tsx`) and do not add a `schema` for frontend validations, all errors are shown right above the the submit. Those are errors created on the server side.

Those errors are serialzed by superjson and automatically deserialzed in the client.

However, not all parts of the error are deserialized: The `message` of a `ZodError` is still a string.

This is the network response I see:

```
{"result":null,"error":{"name":"ZodError","message":"[\n  {\n    \"code\": \"too_small\",\n    \"minimum\": 5,\n    \"type\": \"string\",\n    \"inclusive\": true,\n    \"exact\": false,\n    \"message\": \"Pflichtfeld. Mindestens 5 Zeichen.\",\n    \"path\": [\n      \"name\"\n    ]\n  }\n]","statusCode":500},"meta":{"error":{"values":["Error"]}}}
```

This is what the error looks like when inspecting parts of it:
<img width="867" alt="image" src="https://user-images.githubusercontent.com/111561/212896960-06918d61-bb0b-416a-8a07-3c73c5fdd42e.png">

### I think those change would make this situation better:

1. In the onSubmit ([in `new.tsx`, `edit.tsx`](https://github.com/search?q=repo%3Ablitz-js%2Fblitz+%22%5BFORM_ERROR%5D%3A+error.toString%28%29%2C%22&type=code)), stop calling `.toString()` (`[FORM_ERROR]: error.toString(),`) 
  This makes it super hard to work with the returned array in the form component.
  Instead, pass the error object to the form and show `form.error?.message?.at(0)?.message || formError.toString()` in the `Form.tsx`. This would show the zod error message whenever present and fall back to the current behavior.
2. Can superjson be configured in a way, that would automatically deserialize the `message` field as well? I find it unexpected to receive the message as string.

### Run `blitz -v` and paste the output here:

```
% blitz -v
Blitz version: 2.0.0-beta.20 (global)
Blitz version: 2.0.0-beta.20 (local)
macOS Ventura | darwin-arm64 | Node: v18.8.0


 Package manager: npm

  System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 56.98 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.8.0/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.20 => 2.0.0-beta.20
    @blitzjs/next: 2.0.0-beta.20 => 2.0.0-beta.20
    @blitzjs/rpc: 2.0.0-beta.20 => 2.0.0-beta.20
    @prisma/client: 4.6.0 => 4.6.0
    blitz: 2.0.0-beta.20 => 2.0.0-beta.20
    next: 12.2.5 => 12.2.5
    prisma: 4.6.0 => 4.6.0
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.8.4 => 4.9.4
```

**Comment by siddhsuresh** [comment]
Hey @tordans, I took a deeper look at this issue and here are my findings:
1. The `stringified` `message` is due to how the ZodError class is written here in https://github.com/colinhacks/zod/blob/5616f6b505090ebb1775d1d5567d3ee7baa5519d/src/ZodError.ts#L265-L267, so according to me there is no good way for `blitz rpc` to preempt this and change the typing which will cause undesired side effects.
2. Regarding the deserialization of the `error.message` it can be done directly using `JSON.parse(error.message)` which will work in this case as the types used in the message are supported in-built by JSON.
3. Regarding `form.error?.message?.at(0)?.message || formError.toString()`, I feel this would be better to change this in the page rather than in the base component. We could return 
```ts
return {
    [FORM_ERROR]: JSON.parse(error.message).at(0).message || error.toString(),
}
```
What do you think about this?
