### ISSUE TITLE
getBlitzContext() can only be used in React Server Components in Nextjs 13 or higher

### ISSUE THREAD

**Issue by molysulfur** [blitz-js/blitz#4242]
### What is the problem?

when i use next13 i found problem in "invoke function"

i get error  "getBlitzContext() can only be used in React Server Components in Nextjs 13 or higher"

in Page.ts
`
import { gSSP, invoke } from "src/blitz-server"

export const getServerSideProps = gSSP(async ({ ctx }) => {
  const data = await invoke(..., null)
  return { props: { data } }
})

`

in blitz-server.ts
`
export const { gSSP, gSP, api, invoke } = setupBlitzServer({
  plugins: [
    AuthServerPlugin({
      ...authConfig,
      storage: PrismaStorage(db),
      isAuthorized: simpleRolesIsAuthorized,
    }),
    RpcServerPlugin({})
  ],
  logger: BlitzLogger({})
});
`

how i can fix?

**Comment by siddhsuresh** [comment]
Thanks for the issue, this has been fixed in the latest release
@molysulfur upgrade to latest blitz beta 35, and update the import you are using to 
```diff
-import { gSSP, invoke } from "src/blitz-server"
+import {gSSP} from "src/blitz-server"
+import {invoke} from "@blitzjs/rpc"
```

I am closing the issue since this issue has already been fixed. If it is still present in the latest version, please inform and update the issue. Thanks!

**Comment by akboolz** [comment]
I get this error in new version when i use ` const user = await invoke(getCurrentUser, {})` in page.tsx.

Internal error: Error: getBlitzContext() can only be used in React Server Components in Nextjs 13 or higher
web-dash:dev:     at  \node_modules\.pnpm\@blitzjs+auth@2.0.0-beta.35_blitz@2.0.0-beta.35_next@13.5.4\node_modules\@blitzjs\auth\dist\chunks\auth-plugin.cjs:165:13

**Comment by tordans** [comment]
@akboolz Had the same problem after updating to .35 but [using the fix](https://github.com/blitz-js/blitz/issues/4242#issuecomment-1785199810) to import invoke like `import {invoke} from "@blitzjs/rpc"` solved the issue for me.

**Comment by akboolz** [comment]
@tordans

 Well its not the same I think. Because my query `getCurrentUser` depends on blitz Ctx ( so we can get session inside query ).

In blitz docs: 
`Note we cannot directly import invoke from @blitzjs/rpc due to the necessity to run the required middleware in order to make it work effectively.`

So `invoke` in this case needs to imported from 'blitz-server' not `@blitzjs/rpc`.
import { useAuthenticatedBlitzContext, invoke } from '../blitz-lib/blitz-server'

Otherwise session will undefined ( i guess because auth middleware was not applied ):

`
TypeError: Cannot destructure property 'session' of 'undefined' as it is undefined.
web-dash:dev:     at getCurrentUser (../../web-apis/dash-api/user/queries/getCurrentUser.ts:8:73
`

My sample code in `page.tsx` ( the idea is to get authed user on server ) where I get  error "getBlitzContext() can only be used in React Server Components in Nextjs 13 or higher"

`
import { useAuthenticatedBlitzContext, invoke } from '../blitz-lib/blitz-server'
import { DashboardLayout } from '../components/dashboard/DashboardLayout'
import getCurrentUser from 'dash-api/user/queries/getCurrentUser'

const DashboardPage = async () => {
  await useAuthenticatedBlitzContext({
    redirectTo: '/auth/login',
  })

  const user = await invoke(getCurrentUser, {})

  return (
    <DashboardLayout
      pageTitle="Dashboard"
      dasboardHeader="Dashboard"
      user={user}
    />)
`

The strange thing is that it works on first load but after chainging code / page refresh / link click, this error shows up.

**Comment by tordans** [comment]
@akboolz that would be a question for @siddhsuresh.

**Comment by siddhsuresh** [comment]
@akboolz to be more clear, all usages of `invoke` in the app directory only in React Server components should be from `app/blitz-server` (wherever the file is) and in all pages directory and in Client Components use the import from `@blitzjs/rpc`

Hope this solves your issue.

**Comment by tordans** [comment]
@siddhsuresh we upgraded our app from beta .34 to beta .35 and we now have the same issue with the missing session when `getCurrentUser`, which requires a session/Ctx.

Please reopen this issue.

**Comment by siddhsuresh** [comment]
@tordans @tordans can you give it a try in the latest beta 36?

**Comment by tordans** [comment]
@siddhsuresh I am getting super confused by this error. It is there on one day and gone the next 😞. 

I am removing `/.next` and `/node_modules` before each test to have a clean test setup, but still the results change from day to day.

The error I see, when I see it (in both the test app and our real app), is …

```
Error: getBlitzContext() can only be used in React Server Components in Nextjs 13 or higher
    at /Users/foo/blitz-test-app-directory-error/node_modules/@blitzjs/auth/dist/chunks/auth-plugin.cjs:165:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:533:9)
    at process.processTimers (node:internal/timers:507:7)
```

I will try again next week…

I can say that the behavior is different between dev and production env.

In case someone want to add data points, here is my test setup:
- https://github.com/FixMyBerlin/blitz-test/blob/main/src/app/get-current-user-ctx/page.tsx 
   with `npm run bleach && npm run dev`
- https://github.com/FixMyBerlin/blitz-test/blob/main/src/app/get-current-user-ctx/page.tsx 
   with `npm run bleach && npm run build && npm run start`
- https://github.com/FixMyBerlin/blitz-test/blob/main/src/app/get-current-user-invoke/page.tsx 
   with `npm run bleach && npm run dev`
- https://github.com/FixMyBerlin/blitz-test/blob/main/src/app/get-current-user-invoke/page.tsx 
   with `npm run bleach && npm run build && npm run start`

(And a similar test for https://github.com/FixMyBerlin/atlas-app/blob/develop/src/app/regionen/(index)/_components/RegionListNonpublic.tsx)
