### ISSUE TITLE
Default build command hangs without database

### ISSUE THREAD

**Issue by dwightwatson** [blitz-js/blitz#470]
### What is the problem?

Deploying a fresh Blitz project to now - before I have set up a database. I would assume this is an acceptable use-case for Blitz.

The default build command is `blitz db migrate && blitz build` - but if there is no database configured it will just hang forever and never progress past `blitz db migrate`.

```
14:34:51.191  Running "yarn run build"
14:34:51.357  yarn run v1.22.0
14:34:51.380  $ blitz build
14:34:51.448  You are using alpha software - if you have any problems, please open an issue here:
14:34:51.448    https://github.com/blitz-js/blitz/issues/new/choose
```

I would expect if `blitz db migrate` doesn't have a valid configuration for a database it should just skip and move on, or fail loudly so the developer can remove that build step. Though - it would be a nice experience for a fresh app to deploy easily.

### Steps to Reproduce: 

```
$ blitz new now-app
$ cd now-app
$ now
```
Continue through all default now settings and watch the deployment hang.

### Versions:

```
debug: local
debug: pkgPath: /Users/Dwight/Sites/blitz-app/node_modules/@blitzjs/cli 

macOS Catalina | darwin-x64 | Node: v14.1.0

blitz: 0.9.0 (global)
blitz: 0.9.0 (local)
```

**Comment by flybayer** [comment]
You're totally right @dwightwatson!

Did you experience this locally or when deploying to production?

The hang is because it's prompting you to enter a name for the initial migration.

We can't just fail silently for this because we don't know if the migrate command should actually fail or not.

Probably the solution is to remove the db migrate command from the default build script. Then we'll just have to add this to the documentation on deploying to production.
