### ISSUE TITLE
Generate Prisma Client w/o Migrating

### ISSUE THREAD

**Issue by dajinchu** [blitz-js/blitz#542]
### What do you want and why?

Some way to generate the prisma client so that blitz apps can be fully built without forcing migrations to happen at build time.

### Possible implementation(s)

If we want to avoid ORM-coupling, this is kind of tough. In my opinion, prisma client would be generated as part of `blitz build`.

---

## Edit by @flybayer 

[See this comment below](https://github.com/blitz-js/blitz/issues/542#issuecomment-633617006) on how exactly to do this.

**Comment by flybayer** [comment]
Running this via `blitz build` is a good idea.

We can expose a build hook to plugins once we add plugins, but for now we can hard code it. And fail silently if prisma isn't installed.

**Comment by peaonunes** [comment]
Hey, I'm afraid I did not understand the issue. What do you mean by:
> blitz apps can be fully built without forcing migrations to happen at build time

I thought the app would be fully built after `blitz new`.

**Comment by flybayer** [comment]
So if you are using Prisma, then prisma client must be generated into your project at `node_modules/.prisma/`

In a non-Blitz app, you would do this via `prisma generate`.

In a Blitz app, you do that via `blitz db migrate`, which both runs `prisma migrate` and `prisma generate`.

DJ wants a way to have the prisma client generated without running `blitz db migrate`.

---

We are already automatically generating prisma client on `blitz start` in development [with this line of code](https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/start.ts#L39).

So what needs to happen for this issue is do the same thing in two other places:

1. [This line used for `blitz start --production`](https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/start.ts#L37)
2. [And this line used for `blitz build`](https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/build.ts#L31)

Both of those will require a small change in the server package for the `prod.ts` and `build.ts` files. Basically do the same thing that's already done in `dev.ts`

**Comment by ganeshmani** [comment]
@flybayer I would like to work on this issue. if that's okay

**Comment by flybayer** [comment]
@ganeshmani yeah for sure!
