### ISSUE TITLE
Implement session management

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#577]
Here's the full session management RFC: #475

@rishabhpoddar has finished the pseudo code for this part of the **Essential** method: https://github.com/blitz-js/drafts/pull/10

Here's the [rendered version of his pseudo code](https://github.com/blitz-js/drafts/blob/session-pseudo-code/session-pseudo-code.md).

**Comment by rishabhpoddar** [comment]
An important point: The expiry of the session is updated on use of the session. This does not happen for each request since it would mean that we would have to update the set-cookie + the public data token on the frontend for each request which is inefficient (we will have to do a localstorage write for each request to save the public token). Instead, it happens for all non-GET api requests that happen anytime after 1/4th the session expiry time has passed already.

The reason for doing it for non-GET API requests is that we cannot update the public token info on the frontend's localstorage if the user has done a browser level navigation to the site. If we did do it for GET APIs there is a good chance that it might lead to the frontend code seeing that the session exists even though it actually doesn't. 

I am happy to change this behaviour or go into a more detailed explanation.
