### ISSUE TITLE
No css-modules templates when scaffolding a new blitz app

### ISSUE THREAD

**Issue by jay-jlm** [blitz-js/blitz#806]
App scaffolding (ie, `blitz new myApp`) currently generates styles via `<style jsx>` and `<style jsx global />` tags inside `index.tsx`.

### Possible implementation(s)

1. Add --use-css-modules flag support to the `blitz new`cli command.
2. Generate global styles in `global.styles.css` and add the corresponding import statement to `_app.tsx`.
3. Generate index page styles in `index.module.css` and add the corresponding import statement to` index.tsx`.

**Comment by flybayer** [comment]
Hey @jay-jlm. Can you share more about the motivation behind your request?

The `<style jsx>` items in new apps are meant to be deleted. They are simply there so that the new app page doesn't look extremely ugly :)

**Comment by jay-jlm** [comment]
Got it,  if it is supposed to be removed it indeed makes sense too keep evrything inside a single file.
Looking forward to having first-class support for sass and css modules in the future, thou.
Right now I had do manually install sass and create the css/scss files by hand, hopefully these steps can be automated in the future.

**Comment by flybayer** [comment]
We already have [first class support for sass](https://blitzjs.com/docs/css#sass-support), but we don't have it installed by default. We don't have any styling solution installed by default since everyone has a different approach.

However, I definitely want to add a prompt when you run `blitz new` that shows the top styling options and lets you select one! My current focus is getting auth fully finished. Later I can move on to improving new app generation with options like this. But anyone else is welcome to work on this now if they want!

**Comment by flybayer** [comment]
I'm going to go ahead and close this since there's no direct action to take on this. We'll address a prompt for styling options separately.
