### ISSUE TITLE
Use FormData to simplify forms

### ISSUE THREAD

**Issue by jeremylynch** [blitz-js/blitz#814]
### What do you want and why?

Use FormData to parse forms at onSubmit event (in templates). This allows making adding inputs to forms easier and faster. 

Read more about this implementation [here](https://mattboldt.com/2020/05/02/formdata-with-react-hooks-and-fetch/). 

### Possible implementation(s)

```js
<PracticeForm
  initialValues={{}}
  onSubmit={async (event) => {
    const data = new FormData(event.target)
    let json = Object.fromEntries(data)
    try {
      const practice = await createPractice({ data: json })
      alert("Success!" + JSON.stringify(practice))
      router.push("/practices/[practiceId]", `/practices/${practice.id}`)
    } catch (error) {
      alert("Error creating practice " + JSON.stringify(error, null, 2))
    }
  }}
/>
```

Feedback? Happy to submit a PR for this!

**Comment by flybayer** [comment]
Hey @jeremylynch, thank you so much for the suggestion! Really appreciate it!

We are getting ready to do even better than FormData :) We are adding ability to select between react-final-form, react-hook-form, and formik :D 

So I'll go ahead and close that since form library integration is imminent

**Comment by alexfinnarn** [comment]
@flybayer I'm trying to look for why react-final-form is recommended over other form solutions in the installer, but this issue is the best place I've seen about adding the selection ability...I guess I didn't search PRs but thought there might be a related issue.

Is there some issue/PR comment thread/doc that details the thought process behind providing form options and recommendations?

The last time I checked on form solutions, in general, people seemed to be choosing react-hook-form as the default, but I know how fast the JS world moves and now I guess I have to check again. I've also used Formik but find that solution to be a bit heavier than what I need.

Maybe a sentence or two in https://blitzjs.com/docs/tutorial#writing-a-minimal-form would be good to add. I haven't seen where the form dependencies are added in code so am a bit confused about how things are supposed to be set up for forms at step #1 of `blitz new`.

I'll go off and check out all the three options again, but I feel like most project generators have blurbs about each step of the process and why they recommend one solution over the other when you're offered choices and not yes/no answers.

**Comment by flybayer** [comment]
@alexfinnarn hey good question!

Here's the full discussion we had on form libraries: https://github.com/blitz-js/blitz/discussions/768

And good idea on adding docs on this. Would you be interested in taking a shot at adding a doc page? Probably we can add a dedicated page for "Creating a new app" that covers stuff like this.

**Comment by alexfinnarn** [comment]
I was going to layer Blitz on top of an existing Next project, but now I am just going to add some of the individual pieces Blitz uses and use the project as a reference tool. I'm coming from using very large, abstracted frameworks, like Drupal in PHP, and have been trying to work towards less code and fewer abstractions. 

So, I'll take a rain check on contributing to docs, but I'll continue to watch Blitz, Redwood, and the like as they progress. I like the direction I'm seeing, but just not enough time to eclipse the features and battle testing of 20-year old PHP frameworks I'm more used to...but then they got way bloated, which is always a concern the more successful your project becomes. 

I will say that from #768 it seems like most people like react-hook-form, even if their explanations have more gut feelings than hard facts. If Blitz has telemetry, then do you have numbers on which options people choose? Adding that functionality would put any debate to rest and you could monitor trends as time progresses.
