### ISSUE TITLE
Ask to install blitz-cli globally

### ISSUE THREAD

**Issue by hardfire** [blitz-js/blitz#877]
### What do you want and why?

`yarn start` should check if `blitz` is installed globally and suggest if the user wants to install blitz globally.

### Possible implementation(s)

How might we do this?

I'm not sure, but i'll dig into the repository to figure out how we could do this. 

### Additional context

I cloned a blitz app on my computer and ran `yarn` followed by `yarn start` everything worked fine without having `blitz` cli available. This behavior is expected. 

`expo` does this nice thing where it asks if the user wants to install `expo-cli` globally. It would be a nice experience if we had a similar experience with blitz

![image](https://user-images.githubusercontent.com/513457/90096803-240c5200-dd54-11ea-87c2-cf5ae9170641.png)

**Comment by merelinguist** [comment]
Thanks for the suggestion! I’d like to hear others’ input on this first, though. FWIW, I would be hesitant to add this, since it makes it seems like installing the CLI globally is compulsory, when it in reality it isn’t. I don’t know how Expo does this, but maybe if the user says no the first time, we could then not ask again?

**Comment by flybayer** [comment]
Thanks @hardfire! I agree with @merelinguist. If the global CLI was actually required, then this would totally make sense. But it's not required.

Also, in all our docs we encourage installing the global CLI, so if someone hasn't actually done so, there's a good chance they didn't want to.

**Comment by merelinguist** [comment]
Closing this based on the feedback.
