### ISSUE TITLE
Can't import enum from prisma client

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#937]
### What is the problem?

We want to do `import { Tree } from '@prisma/client'` and use enum in client-side code. But currently this results in `undefined`. 

I'm pretty sure the problem is that we use a null-loader for prisma client [in our webpack config](https://github.com/blitz-js/blitz/blob/canary/packages/server/src/with-blitz.ts#L30).

So we should try removing that line and see if it works. I think prisma changed something earlier that makes that null-loader not needed.

### Steps to Reproduce

```
// schema.prisma
enum Tree {
  ARBORVITAE
  YELLOWBIRCH
  BLACKASH
  DOUGLASFIR
  OAK
}
```

```ts
import {Tree} from '@prisma/client'

//console.log(Tree) => undefined
```

**Comment by osirvent** [comment]
I have an app with prisma 2.0.1 and I can use enum type through import "db"

**Comment by osirvent** [comment]
I`ve just tried with a new app with prisma 2.5.1. and it IS available.

the enum must be used on a model and then `blitz db migrate`

**Comment by flybayer** [comment]
🤔 interesting!

**Comment by SigurdMW** [comment]
Is this still an issue that needs to be worked on? I might be able to help out!

**Comment by flybayer** [comment]
@SigurdMW yes!

**Comment by SigurdMW** [comment]
So after removing the null-loader i get this
![image](https://user-images.githubusercontent.com/6359003/92032456-77c5f600-ed6a-11ea-9eea-5d6ea575ce0d.png)
Any tip on where to go next?

**Comment by flybayer** [comment]
I just had an idea. Add a webpack config thing for the client build, so it only loads the prisma type file, not the code.

- server: `import '@prisma/client'` resolves to `node_modules/@prisma/client/index.js`
- client: `import '@prisma/client'` resolves to `node_modules/@prisma/client/index.d.ts`

This _might_ can be accomplished by adding an alias via [webpack resolve](https://webpack.js.org/configuration/resolve/) for the client webpack config.

**Comment by SigurdMW** [comment]
Ok so I have tried what you said. Added a resolve to the wepack config, and tried both with and without the `null-loader` for `@prisma/client` in file `packages/server/src/with-blitz.ts`:
![image](https://user-images.githubusercontent.com/6359003/92114603-6673fc80-edf1-11ea-868f-f378fe8a67e8.png)

getting this in the console. 
![image](https://user-images.githubusercontent.com/6359003/92114876-d8e4dc80-edf1-11ea-858c-908590007da3.png)

And when adding a `ts-loader`, I get this since it's just a type file:
![image](https://user-images.githubusercontent.com/6359003/92117886-0d5a9780-edf6-11ea-8ba1-4d7848393ba3.png)

I'm not quite sure what is the best way forward here, could it be a solution to create our own declaration file that re-exports the relevant types from @prisma/client?

**Comment by engelkes-finstreet** [comment]
As additional information. I just tried this in my own project with Prisma _2.6.1_.

`import { PlayerType } from "@prisma/client"` leads to the undefined behaviour as described by @flybayer.
`import { PlayerType } from "db"` leads to this error 
_TypeError: _prisma_client__WEBPACK_IMPORTED_MODULE_0__.PrismaClient is not a constructor_

**Comment by flybayer** [comment]
So it turns out this was simply a misunderstanding of Typescript enums. Typescript enums are not available at runtime because they are a type only thing.

The enum type itself can be used in Blitz just fine. If you need the values at runtime, like to display in a select box or something, you need to define those values yourself via JS.

**Comment by flybayer** [comment]
> So it turns out this was simply a misunderstanding of Typescript enums. Typescript enums are not available at runtime because they are a type only thing.

Actually I was wrong about this 🤦 

This is still an issue.

I think we might need some changes in Prisma to fix this. This could be fixed by prisma generating a server entry point and a browser entry point, where the browser entry point only has the enum and client-safe code. If they did that, then we can stop using null-loader.

Can someone open an issue in the [prisma repo](https://github.com/prisma/prisma) for this?

**Comment by joaopaulobdac** [comment]
@flybayer There is this one already: https://github.com/prisma/prisma/issues/1272

I tried to import a database enum to use inside a form validation schema on the frontend utilizing webpack's IgnorePlugin to not bundle the prisma runtime along with it: 

```js
plugins: [
    new IgnorePlugin({ resourceRegExp: /@prisma\/client\/runtime/ })
]
```

There were no compilations errors, but the code crashes when the browser executes the bundle because webpack still includes the entire `index.js` file instead of tree-shaking so that only the enum is included...

> This could be fixed by prisma generating a server entry point and a browser entry point, where the browser entry point only has the enum and client-safe code.

I think this is the only option

**Comment by jan-wilhelm** [comment]
[This comment](https://github.com/prisma/prisma/issues/1272#issuecomment-744329613) looks like it should work now with the latest Prisma version
